apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: telegraf
  namespace: network-monitoring
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: telegraf
          image: pleasebenice/telegraf-tshark:1.1
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - SYS_ADMIN
          volumeMounts:
            - name: telegraf-config
              mountPath: /etc/telegraf/telegraf.conf
              subPath: telegraf.conf
            - name: host-root
              mountPath: /host
              readOnly: true
          env:
            - name: INFLUX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: monitoring-secrets
                  key: influxdb-admin-token
            - name: HOST_PROC
              value: /host/proc
            - name: HOST_SYS
              value: /host/sys
            - name: HOST_ETC
              value: /host/etc
      volumes:
        - name: telegraf-config
          configMap:
            name: telegraf-config
        - name: host-root
          hostPath:
            path: /
